Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,12 +1,7 @@
-# You can override the included template(s) by including variable overrides
-# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
-# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
-# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
-# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
-# Note that environment variables can be set in several places
-# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
 stages:
-- build
+  - build
+  - test
+
 variables:
   IMAGE_NAME: sdns-new
   DOCKER_REGISTRY: registry.gitlab.com
@@ -15,36 +10,39 @@ variables:
   DOCKER_BUILDKIT: 1
   DOCKER_CLI_EXPERIMENTAL: enabled
   DOCKER_PLATFORM: linux/arm64
+
 build_and_push:
   image: docker:27
   stage: build
   services:
-  - name: docker:27-dind
-    command:
-    - "--experimental"
-    - "--storage-driver=overlay2"
+    - name: docker:27-dind
+      command:
+        - "--experimental"
+        - "--storage-driver=overlay2"
   before_script:
-  - apk add --no-cache git
-  - git --version
-  - echo "Logging into GitLab Container Registry..."
-  - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
-  - |
-    if [ $? -ne 0 ]; then
-      echo "Login failed, exiting pipeline."
-      exit 1
-    fi
+    - apk add --no-cache git go  # Tambahkan Go untuk go mod tidy
+    - git --version
+    - go version
+    - echo "Logging into GitLab Container Registry..."
+    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
+    - |
+      if [ $? -ne 0 ]; then
+        echo "Login failed, exiting pipeline."
+        exit 1
+      fi
+    - go mod tidy  # Sinkronkan dependensi
   script:
-  - |
-    BUILD_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
-    VERSION="build-$BUILD_TIMESTAMP"
-    echo "Building Docker image version: ${VERSION}"
-    docker buildx ls || docker run --rm --privileged tonistiigi/binfmt:latest --install all
-    docker buildx use || docker buildx create --use
-    docker buildx inspect --bootstrap
-    docker buildx build \
-      --platform $DOCKER_PLATFORM \
-      --push \
-      --no-cache \
-      --tag $DOCKER_IMAGE:$VERSION \
-      --tag $DOCKER_IMAGE:$DOCKER_TAG_LATEST \
-      . || { echo "Docker build or push failed"; exit 1; }
+    - |
+      BUILD_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
+      VERSION="build-$BUILD_TIMESTAMP"
+      echo "Building Docker image version: ${VERSION}"
+      docker buildx ls || docker run --rm --privileged tonistiigi/binfmt:latest --install all
+      docker buildx use || docker buildx create --use
+      docker buildx inspect --bootstrap
+      docker buildx build \
+        --platform $DOCKER_PLATFORM \
+        --push \
+        --no-cache \
+        --tag $DOCKER_IMAGE:$VERSION \
+        --tag $DOCKER_IMAGE:$DOCKER_TAG_LATEST \
+        . || { echo "Docker build or push failed"; exit 1; }
